import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

function genToken() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let t = '';
  for (let i = 0; i < 32; i++) t += chars[Math.floor(Math.random() * chars.length)];
  return t;
}

const ESTADO_LABEL_ES = {
  buscando: 'Buscando información',
  informacion_recibida: 'Información recibida',
  visto_no_confirmado: 'Visto — sin confirmar',
  encontrado_con_vida: 'Encontrado/a con vida',
  en_hospital_refugio: 'En hospital o refugio',
  fallecido_reportado: 'Fallecimiento reportado',
  caso_cerrado: 'Caso cerrado',
};

const ESTADO_LABEL_EN = {
  buscando: 'Searching for information',
  informacion_recibida: 'Information received',
  visto_no_confirmado: 'Seen — unconfirmed',
  encontrado_con_vida: 'Found alive',
  en_hospital_refugio: 'In hospital or shelter',
  fallecido_reportado: 'Death reported',
  caso_cerrado: 'Case closed',
};

const ESTADO_COLOR = {
  buscando: '#D48C2E',
  informacion_recibida: '#3B72C4',
  visto_no_confirmado: '#E87A30',
  encontrado_con_vida: '#2E7D32',
  en_hospital_refugio: '#0097A7',
  fallecido_reportado: '#616161',
  caso_cerrado: '#9E9E9E',
};

const ESTADO_EMOJI = {
  buscando: '🔎',
  informacion_recibida: '📋',
  visto_no_confirmado: '👁️',
  encontrado_con_vida: '✅',
  en_hospital_refugio: '🏥',
  fallecido_reportado: '🕯️',
  caso_cerrado: '📁',
};

function buildEmailHtml({ nombre, estadoCaso, ubicacion, mensaje_extra, updateLink, profileLink, lang }) {
  const es = lang !== 'en';
  const labelEs = ESTADO_LABEL_ES[estadoCaso] || estadoCaso;
  const labelEn = ESTADO_LABEL_EN[estadoCaso] || estadoCaso;
  const label = es ? labelEs : labelEn;
  const color = ESTADO_COLOR[estadoCaso] || '#1A1F2E';
  const emoji = ESTADO_EMOJI[estadoCaso] || '📋';

  const isGood = ['encontrado_con_vida', 'en_hospital_refugio'].includes(estadoCaso);
  const isBad = estadoCaso === 'fallecido_reportado';

  const headerBg = isGood ? '#E8F5E9' : isBad ? '#F5F5F5' : '#FFF8EE';
  const headerBorder = isGood ? '#A5D6A7' : isBad ? '#BDBDBD' : '#E6C195';

  const abrazo = es
    ? (isGood ? 'Hay buenas noticias. Estamos contigo.' : isBad ? 'Estamos con tu familia en este momento difícil.' : 'Estamos contigo. Seguimos buscando información.')
    : (isGood ? 'There is good news. We are with you.' : isBad ? 'We are with your family in this difficult moment.' : 'We are with you. We keep looking for information.');

  const cta_label = es ? 'Ver información completa' : 'View full information';
  const update_label = es ? 'Actualizar mi estado (si eres tú)' : 'Update my status (if this is you)';
  const antiext = es
    ? '⚠️ Nunca envíes dinero a cambio de información. STATUSVZLA.com no autoriza pagos ni rescates privados. Si alguien pide dinero, es una estafa.'
    : '⚠️ Never send money in exchange for information. STATUSVZLA.com does not authorize payments or private rescue fees. If someone asks for money, it\'s a scam.';
  const footer_msg = es ? 'Este mensaje fue generado automáticamente por STATUSVZLA.com — Sistema de respuesta a emergencias.' : 'This message was automatically generated by STATUSVZLA.com — Emergency response system.';

  return `<!DOCTYPE html>
<html lang="${es ? 'es' : 'en'}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>STATUSVZLA</title></head>
<body style="margin:0;padding:0;background:#F4F4F8;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F4F4F8;padding:24px 16px;">
    <tr><td align="center">
      <table width="100%" style="max-width:520px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">

        <!-- Header brand -->
        <tr><td style="background:#1A1F2E;padding:20px 28px;">
          <p style="margin:0;color:#fff;font-size:20px;font-weight:900;letter-spacing:-0.5px;">STATUS<span style="color:#D48C2E;">VZLA</span><span style="color:#D48C2E;font-size:14px;">.com</span></p>
          <p style="margin:4px 0 0;color:#9CA3AF;font-size:11px;">${es ? 'Sistema de respuesta a emergencias · Venezuela' : 'Emergency response system · Venezuela'}</p>
        </td></tr>

        <!-- Status card -->
        <tr><td style="padding:24px 28px 0;">
          <div style="background:${headerBg};border:1.5px solid ${headerBorder};border-radius:12px;padding:20px;text-align:center;">
            <div style="font-size:40px;margin-bottom:8px;">${emoji}</div>
            <p style="margin:0 0 6px;font-size:13px;color:#6B7280;font-weight:600;text-transform:uppercase;letter-spacing:0.5px;">${es ? 'Estado actualizado' : 'Status updated'}</p>
            <h1 style="margin:0 0 4px;font-size:22px;font-weight:900;color:#1A1F2E;">${nombre}</h1>
            <div style="display:inline-block;background:${color};color:#fff;font-size:13px;font-weight:700;padding:6px 16px;border-radius:50px;margin-top:8px;">${label}</div>
            ${ubicacion ? `<p style="margin:12px 0 0;font-size:12px;color:#6B7280;">📍 ${ubicacion}</p>` : ''}
          </div>
        </td></tr>

        <!-- Human message -->
        <tr><td style="padding:20px 28px;">
          <p style="margin:0 0 12px;font-size:15px;color:#374151;line-height:1.6;font-weight:500;">${abrazo}</p>
          ${mensaje_extra ? `<p style="margin:0 0 12px;font-size:14px;color:#4B5563;line-height:1.6;background:#F9FAFB;border-radius:10px;padding:14px;">"${mensaje_extra}"</p>` : ''}
          <p style="margin:0;font-size:13px;color:#6B7280;line-height:1.5;">${es ? 'Esta alerta fue enviada porque te registraste para recibir actualizaciones sobre esta persona.' : 'This alert was sent because you subscribed to updates about this person.'}</p>
        </td></tr>

        <!-- CTA buttons -->
        <tr><td style="padding:0 28px 20px;">
          <a href="${profileLink}" style="display:block;background:#1A1F2E;color:#fff;text-decoration:none;text-align:center;padding:14px;border-radius:10px;font-weight:700;font-size:14px;margin-bottom:8px;">${cta_label}</a>
          ${updateLink ? `<a href="${updateLink}" style="display:block;background:#fff;border:2px solid #D48C2E;color:#D48C2E;text-decoration:none;text-align:center;padding:12px;border-radius:10px;font-weight:700;font-size:13px;">${update_label}</a>` : ''}
        </td></tr>

        <!-- Anti-extortion -->
        <tr><td style="padding:0 28px 20px;">
          <div style="background:#FDF1F0;border:1px solid #E8B4B0;border-radius:10px;padding:14px;">
            <p style="margin:0;font-size:12px;color:#B83A52;line-height:1.5;">${antiext}</p>
          </div>
        </td></tr>

        <!-- Footer -->
        <tr><td style="background:#F9FAFB;padding:16px 28px;border-top:1px solid #F3F4F6;">
          <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.5;">${footer_msg}</p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const { persona_id, tipo_evento, datos_persona } = await req.json();

    if (!persona_id) return Response.json({ error: 'persona_id requerido' }, { status: 400 });

    const subs = await base44.asServiceRole.entities.Suscripciones.filter({ persona_id, activa: true });
    if (!subs || subs.length === 0) return Response.json({ ok: true, notificados: 0 });

    const nombre = datos_persona?.nombre_completo || 'La persona';
    const estadoCaso = datos_persona?.estado_caso || 'buscando';
    const ubicacion = datos_persona?.ubicacion || '';

    const esNueva = tipo_evento === 'nueva_busqueda';
    const esEncontrada = tipo_evento === 'persona_encontrada';

    const asuntoEs = esNueva
      ? `🔎 Nueva búsqueda registrada: ${nombre}`
      : esEncontrada
        ? `📋 Hay información sobre ${nombre}`
        : `${ESTADO_EMOJI[estadoCaso] || '📋'} Actualización: ${nombre}`;

    const asuntoEn = esNueva
      ? `🔎 New search registered: ${nombre}`
      : esEncontrada
        ? `📋 There is information about ${nombre}`
        : `${ESTADO_EMOJI[estadoCaso] || '📋'} Update: ${nombre}`;

    const APP_URL = 'https://app.statusvzla.com';

    let notificados = 0;
    for (const sub of subs) {
      const token = genToken();
      const expira = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
      await base44.asServiceRole.entities.TokensAutoUpdate.create({
        token, persona_id, email_destino: sub.email_notificacion, usado: false, expira,
      });

      const updateLink = `${APP_URL}/actualizar-estado?token=${token}`;
      const profileLink = `${APP_URL}/persona?id=${persona_id}&token=${token}`;
      const lang = 'es'; // default to Spanish for Venezuela context

      const htmlBody = buildEmailHtml({
        nombre,
        estadoCaso: esNueva ? 'buscando' : estadoCaso,
        ubicacion,
        mensaje_extra: datos_persona?.mensaje || '',
        updateLink,
        profileLink,
        lang,
      });

      const textBody = `${asuntoEs}\n\n${nombre} — ${ESTADO_LABEL_ES[estadoCaso] || estadoCaso}\n\n${ubicacion ? `📍 ${ubicacion}\n\n` : ''}Si eres ${nombre} o puedes actualizar esta información:\n${updateLink}\n\n⚠️ Nunca envíes dinero a cambio de información. STATUSVZLA.com no autoriza pagos ni rescates privados.\n\n— Equipo STATUSVZLA.com`;

      await base44.asServiceRole.integrations.Core.SendEmail({
        to: sub.email_notificacion,
        subject: asuntoEs,
        body: htmlBody,
        from_name: 'STATUSVZLA.com',
      });

      await base44.asServiceRole.entities.NotificacionesUsuario.create({
        user_id: sub.user_id,
        tipo: tipo_evento,
        titulo: asuntoEs,
        mensaje: textBody,
        leida: false,
        ref_id: persona_id,
        link_ref: `/actualizar-estado?token=${token}`,
      });

      notificados++;
    }

    return Response.json({ ok: true, notificados });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});