// ── Contenido de la guía educativa de edificios dañados ──
// Extraído de GuiaEdificios.jsx para mantener el archivo de página liviano.

export const SECCIONES = [
  {
    id: 'antes',
    emoji: '🏠',
    es: '¿Qué hacer ANTES de entrar a un edificio?',
    en: 'What to do BEFORE entering a building?',
    color: '#1A5276',
    bg: '#EBF5FB',
    border: '#AED6F1',
    items: [
      {
        es: '👁️ Observa desde afuera primero',
        en: '👁️ Observe from outside first',
        desc_es: 'Antes de acercarte, examina visualmente el edificio desde una distancia segura. Busca grietas en fachada, paredes inclinadas o escombros en la entrada.',
        desc_en: 'Before approaching, visually examine the building from a safe distance. Look for cracks in the facade, leaning walls, or debris at the entrance.',
      },
      {
        es: '👃 Huele el ambiente',
        en: '👃 Smell the air',
        desc_es: 'Si detectas olor a gas (similar a huevo podrido), NO entres. Aleja a todos y llama a los bomberos inmediatamente.',
        desc_en: 'If you detect a gas smell (like rotten eggs), DO NOT enter. Move everyone away and call firefighters immediately.',
      },
      {
        es: '👂 Escucha antes de avanzar',
        en: '👂 Listen before moving',
        desc_es: 'Crujidos, sonidos de desprendimiento o ruidos inusuales indican que la estructura está cediendo. Detente y retrocede.',
        desc_en: 'Creaking, crumbling sounds, or unusual noises indicate the structure is giving way. Stop and go back.',
      },
      {
        es: '🔦 Luz y cables eléctricos',
        en: '🔦 Lights and electrical wires',
        desc_es: 'Cables caídos, postes inclinados o chispas visibles = peligro eléctrico. Mantén distancia mínima de 10 metros y no toques nada metálico.',
        desc_en: 'Fallen wires, leaning poles, or visible sparks = electrical danger. Keep a minimum distance of 10 meters and do not touch anything metal.',
      },
      {
        es: '🚪 Verifica el estado oficial',
        en: '🚪 Check the official status',
        desc_es: 'Busca el edificio en el directorio CRIS antes de entrar. Si está marcado como "NO ENTRAR", respeta la señalización.',
        desc_en: 'Search the building in the CRIS directory before entering. If it is marked "DO NOT ENTER", respect the signage.',
      },
    ],
  },
  {
    id: 'senales',
    emoji: '🚨',
    es: 'Señales de peligro inmediato',
    en: 'Signs of immediate danger',
    color: '#C0392B',
    bg: '#FDEDEC',
    border: '#F5B7B1',
    items: [
      {
        es: '💥 Grietas en forma de X o diagonal',
        en: '💥 X-shaped or diagonal cracks',
        desc_es: 'Las grietas diagonales en columnas o paredes estructurales indican daño severo. Son más graves que las grietas horizontales o verticales.',
        desc_en: 'Diagonal cracks in columns or structural walls indicate severe damage. They are more serious than horizontal or vertical cracks.',
      },
      {
        es: '🏚️ Piso inclinado o hundido',
        en: '🏚️ Slanted or sunken floor',
        desc_es: 'Si el piso no está nivelado o hay hundimientos visibles, los pilotes o cimientos pueden estar comprometidos. NO entres.',
        desc_en: 'If the floor is not level or there are visible sinkholes, the piles or foundations may be compromised. DO NOT enter.',
      },
      {
        es: '🌊 Humedad inusual o paredes mojadas',
        en: '🌊 Unusual moisture or wet walls',
        desc_es: 'Puede indicar tuberías rotas o infiltración. En combinación con daño estructural, aumenta el riesgo de colapso.',
        desc_en: 'May indicate broken pipes or infiltration. Combined with structural damage, it increases the risk of collapse.',
      },
      {
        es: '🚪 Puertas o ventanas que no cierran',
        en: '🚪 Doors or windows that do not close',
        desc_es: 'Si marcos de puertas o ventanas están deformados, la estructura del edificio se ha movido. Es señal de daño estructural.',
        desc_en: 'If door or window frames are deformed, the building structure has shifted. This is a sign of structural damage.',
      },
      {
        es: '💧 Polvo constante cayendo',
        en: '💧 Constant dust falling',
        desc_es: 'Si ves polvo o pequeños fragmentos de concreto cayendo del techo sin motivo aparente, el edificio puede estar cediendo activamente.',
        desc_en: 'If you see dust or small concrete fragments falling from the ceiling for no apparent reason, the building may be actively collapsing.',
      },
    ],
  },
  {
    id: 'semaforeo',
    emoji: '🚦',
    es: 'Semaforización: ¿Qué significa cada nivel?',
    en: 'Traffic light system: What does each level mean?',
    color: '#1A7A4A',
    bg: '#E6F5ED',
    border: '#A8D8BC',
    imagen: 'https://media.base44.com/images/public/6a3ddf29c9e933d4c38e9646/6bf52e6c5_Infografiaestadodeledificio.png',
    imagenAlt_es: 'Infografía: daño leve, daño moderado, daño grave, colapsado',
    imagenAlt_en: 'Infographic: minor damage, moderate damage, severe damage, collapsed',
    imagenCaption_es: '1. Daño leve · 2. Daño moderado · 3. Daño grave · 4. Colapsado',
    imagenCaption_en: '1. Minor damage · 2. Moderate damage · 3. Severe damage · 4. Collapsed',
    items: [
      {
        es: '🟢 ENTRADA AUTORIZADA',
        en: '🟢 ENTRY AUTHORIZED',
        desc_es: 'Estructura inspeccionada y declarada segura por autoridad competente. Puede haber daños estéticos menores pero la estructura es firme.',
        desc_en: 'Structure inspected and declared safe by competent authority. There may be minor cosmetic damage but the structure is solid.',
      },
      {
        es: '🟡 PRECAUCIÓN — Daño leve',
        en: '🟡 CAUTION — Minor damage',
        desc_es: 'Grietas pequeñas o daños estéticos. La estructura parece firme pero debe ser revisada por un técnico. Entrada con cuidado, mínimo tiempo adentro.',
        desc_en: 'Small cracks or cosmetic damage. The structure appears solid but must be inspected by a technician. Enter with care, minimum time inside.',
      },
      {
        es: '🟠 ENTRADA LIMITADA — Daño moderado',
        en: '🟠 LIMITED ENTRY — Moderate damage',
        desc_es: 'Daños visibles en paredes, piso o escaleras. Solo entrada para rescatistas entrenados o para recuperar documentos esenciales muy rápido.',
        desc_en: 'Visible damage to walls, floor, or stairs. Entry only for trained rescuers or to retrieve essential documents very quickly.',
      },
      {
        es: '🔴 NO ENTRAR — Daño grave o crítico',
        en: '🔴 DO NOT ENTER — Severe or critical damage',
        desc_es: 'Colapso parcial, daño estructural grave o riesgos activos (gas, electricidad, incendio). NADIE debe entrar excepto rescatistas especializados con equipo.',
        desc_en: 'Partial collapse, severe structural damage, or active risks (gas, electricity, fire). NO ONE should enter except specialized rescuers with equipment.',
      },
      {
        es: '💥 COLAPSADO — Zona de rescate activo',
        en: '💥 COLLAPSED — Active rescue zone',
        desc_es: 'Estructura derrumbada. Zona de operaciones de rescate activo. Mantente a distancia mínima de 50 metros. No obstaculices a los rescatistas.',
        desc_en: 'Structure collapsed. Active rescue operations zone. Maintain a minimum distance of 50 meters. Do not obstruct rescuers.',
      },
    ],
  },
  {
    id: 'gas',
    emoji: '💨',
    es: 'Riesgo de gas: protocolo de emergencia',
    en: 'Gas risk: emergency protocol',
    color: '#D35400',
    bg: '#FEF5E7',
    border: '#FAD7A0',
    items: [
      {
        es: '1. No enciendas nada eléctrico',
        en: '1. Do not turn on anything electrical',
        desc_es: 'Ni luces, ni interruptores, ni teléfono cerca de la fuga. Una chispa puede causar explosión.',
        desc_en: 'No lights, no switches, no phone near the leak. A spark can cause an explosion.',
      },
      {
        es: '2. Abre puertas y ventanas',
        en: '2. Open doors and windows',
        desc_es: 'Si puedes hacerlo sin tocar electricidad, ventila el espacio. Muévete rápido pero sin correr para no generar chispas estáticas.',
        desc_en: 'If you can do it without touching electricity, ventilate the space. Move quickly but do not run to avoid generating static sparks.',
      },
      {
        es: '3. Evacúa a todos inmediatamente',
        en: '3. Evacuate everyone immediately',
        desc_es: 'Saca a todas las personas del edificio y aléjalas al menos 100 metros. Nadie regresa hasta que lleguen los bomberos.',
        desc_en: 'Get everyone out of the building and move them at least 100 meters away. No one goes back until firefighters arrive.',
      },
      {
        es: '4. Llama desde afuera del edificio',
        en: '4. Call from outside the building',
        desc_es: 'Bomberos: 171 (CANTV fijo), *1 (Movilnet), 112 (Digitel), 911 (Movistar). Llama solo cuando estés a distancia segura.',
        desc_en: 'Fire: 171 (CANTV landline), *1 (Movilnet), 112 (Digitel), 911 (Movistar). Call only when at a safe distance.',
      },
      {
        es: '5. No regreses aunque "ya no huela"',
        en: '5. Do not go back even if "you can no longer smell it"',
        desc_es: 'El gas puede acumularse en zonas bajas sin ser detectado por el olfato. Solo los bomberos con equipos especiales confirman si es seguro.',
        desc_en: 'Gas can accumulate in low areas without being detectable by smell. Only firefighters with special equipment can confirm if it is safe.',
      },
    ],
  },
  {
    id: 'atrapados',
    emoji: '🆘',
    es: 'Si hay personas atrapadas',
    en: 'If there are trapped people',
    color: '#C0392B',
    bg: '#FDEDEC',
    border: '#E74C3C',
    items: [
      {
        es: '📢 Comunícate sin entrar',
        en: '📢 Communicate without entering',
        desc_es: 'Habla desde afuera en voz alta. Golpea tuberías o paredes si puedes para que la persona sepa que hay ayuda. No entres a estructuras dañadas.',
        desc_en: 'Speak loudly from outside. Bang on pipes or walls if possible so the person knows help is coming. Do not enter damaged structures.',
      },
      {
        es: '📱 Reporta ahora en CRIS',
        en: '📱 Report now in CRIS',
        desc_es: 'Abre la ficha del edificio en CRIS y selecciona "Personas atrapadas". Esto alerta a rescatistas que monitorean la plataforma.',
        desc_en: 'Open the building record in CRIS and select "Trapped people". This alerts rescuers monitoring the platform.',
      },
      {
        es: '🚒 Llama a los bomberos y da ubicación exacta',
        en: '🚒 Call firefighters and give exact location',
        desc_es: 'Da la dirección exacta, número de personas aproximado, si hay gas o fuego, y qué piso o sección del edificio.',
        desc_en: 'Give the exact address, approximate number of people, if there is gas or fire, and which floor or section of the building.',
      },
      {
        es: '🕯️ Marca la posición visible',
        en: '🕯️ Mark the visible position',
        desc_es: 'Si puedes, marca con tela, tiza u objeto visible la ubicación exacta donde está la persona atrapada para guiar a los rescatistas.',
        desc_en: 'If possible, mark with cloth, chalk, or a visible object the exact location of the trapped person to guide rescuers.',
      },
      {
        es: '⏳ No muevas escombros sin entrenamiento',
        en: '⏳ Do not move debris without training',
        desc_es: 'Mover escombros sin técnica puede causar derrumbes secundarios. Espera a los rescatistas. Tu seguridad también importa.',
        desc_en: 'Moving debris without technique can cause secondary collapses. Wait for rescuers. Your safety matters too.',
      },
    ],
  },
  {
    id: 'partes',
    emoji: '🧩',
    es: '¿Qué es una columna, una viga o un muro?',
    en: 'What is a column, a beam or a wall?',
    color: '#6C3483',
    bg: '#F4ECF7',
    border: '#D2B4DE',
    items: [
      {
        es: '🙋 No necesitas saber ingeniería',
        en: '🙋 You do not need to know engineering',
        desc_es: 'No necesitas saber el nombre técnico exacto. Si no estás seguro de qué parte está dañada, selecciona "No sé" en el formulario y sube fotos claras. Con eso basta.',
        desc_en: 'You do not need to know the exact technical name. If you are not sure which part is damaged, select "I don\'t know" in the form and upload clear photos. That is enough.',
      },
      {
        es: '🏛️ Columna',
        en: '🏛️ Column',
        desc_es: 'Es el pilar vertical (casi siempre de concreto) que va de piso a techo y sostiene el peso del edificio. Es uno de los elementos más importantes: si tiene grietas en forma de "X" o se ve el hierro por dentro, es una señal grave.',
        desc_en: 'It is the vertical pillar (usually concrete) that goes from floor to ceiling and holds up the building\'s weight. It is one of the most important elements: if it has "X"-shaped cracks or you can see the rebar inside, that is a serious sign.',
      },
      {
        es: '📏 Viga',
        en: '📏 Beam',
        desc_es: 'Es la pieza horizontal que conecta las columnas y sostiene el techo o el piso de arriba. Grietas cerca de donde la viga se une a la columna son señal de alerta.',
        desc_en: 'It is the horizontal piece that connects the columns and holds up the ceiling or the floor above. Cracks near where the beam meets the column are a warning sign.',
      },
      {
        es: '🧱 Muro portante (muro de carga)',
        en: '🧱 Load-bearing wall',
        desc_es: 'Es una pared gruesa que, además de dividir espacios, también sostiene el peso del edificio. Si tiene grietas en forma de "X" que la atraviesan por completo, es un problema estructural grave.',
        desc_en: 'It is a thick wall that, besides dividing spaces, also holds up the building\'s weight. If it has "X"-shaped cracks that go all the way through it, that is a serious structural problem.',
      },
      {
        es: '🚪 Pared divisoria (tabique)',
        en: '🚪 Partition wall',
        desc_es: 'Es una pared que solo separa cuartos; no sostiene el edificio. Sus grietas suelen ser menos peligrosas (más estéticas que estructurales), pero igual repórtalas.',
        desc_en: 'It is a wall that only separates rooms; it does not hold up the building. Its cracks are usually less dangerous (more cosmetic than structural), but report them anyway.',
      },
      {
        es: '⚠️ ¿Qué grietas preocupan más?',
        en: '⚠️ Which cracks are more concerning?',
        desc_es: 'Las grietas en diagonal o en forma de "X" en columnas, vigas o muros de carga son las más preocupantes. También son señal de riesgo: acero visible, concreto desprendido, paredes inclinadas, puertas o ventanas que ya no cierran, y polvo cayendo sin motivo.',
        desc_en: 'Diagonal or "X"-shaped cracks in columns, beams or load-bearing walls are the most concerning. Also signs of risk: visible rebar, crumbled concrete, leaning walls, doors or windows that no longer close, and dust falling for no reason.',
      },
    ],
  },
  {
    id: 'fotos_guia',
    emoji: '📸',
    es: 'Cómo tomar las fotos correctas',
    en: 'How to take the right photos',
    color: '#1A5276',
    bg: '#EBF5FB',
    border: '#AED6F1',
    imagen: 'https://media.base44.com/images/public/6a3ddf29c9e933d4c38e9646/4b6d2d3de_Infografiainstruccionesfotos.png',
    imagenAlt_es: 'Infografía: foto de fachada, foto del daño en estructura o pared, foto detallada del daño',
    imagenAlt_en: 'Infographic: façade photo, structure or wall damage photo, close-up damage photo',
    imagenCaption_es: 'Ejemplo: 1. Exterior del edificio · 2. Daño en estructura o pared · 3. Daño de cerca',
    imagenCaption_en: 'Example: 1. Building exterior · 2. Damage on structure or wall · 3. Close-up damage',
    items: [
      {
        es: '🔢 Regla de oro: general → detalle → escala',
        en: '🔢 Golden rule: general → detail → scale',
        desc_es: 'Para cada daño toma 3 fotos si puedes: 1) el elemento completo (ej. la columna de piso a techo), 2) la grieta o daño de cerca, y 3) un objeto de referencia (moneda, lápiz) junto al daño para que se note el tamaño. Nunca metas los dedos en la grieta.',
        desc_en: 'For each damage, take 3 photos if you can: 1) the whole element (e.g. the column from floor to ceiling), 2) the crack or damage close-up, and 3) a reference object (coin, pencil) next to the damage so its size is clear. Never put your fingers inside the crack.',
      },
      {
        es: '🏠 Foto de fachada',
        en: '🏠 Façade photo',
        desc_es: 'Ayuda al inspector a ubicar el edificio. Tómala completa desde la acera de enfrente, que se vea el número o un punto de referencia cercano.',
        desc_en: 'Helps the inspector locate the building. Take it in full from the opposite sidewalk, showing the number or a nearby landmark.',
      },
      {
        es: '🧱 Fotos de daño estructural',
        en: '🧱 Structural damage photos',
        desc_es: 'Columnas, vigas o muros con grietas, partidos o aplastados. Prioriza grietas en diagonal o en forma de "X". Siempre desde un lugar seguro.',
        desc_en: 'Columns, beams or walls that are cracked, split or crushed. Prioritize diagonal or "X"-shaped cracks. Always from a safe place.',
      },
      {
        es: '🪜 Pisos, techos y escaleras',
        en: '🪜 Floors, ceilings and stairs',
        desc_es: 'Fotografía pisos hundidos o desnivelados, techos con hundimiento visible y escaleras rotas o separadas de la pared.',
        desc_en: 'Photograph sunken or uneven floors, ceilings with visible sagging, and broken stairs or stairs detached from the wall.',
      },
      {
        es: '⚡ Riesgos: gas, electricidad, fuego',
        en: '⚡ Hazards: gas, electricity, fire',
        desc_es: 'Cables caídos, tableros con chispas o señales de fuga de gas — siempre fotografiados desde lejos, nunca acercándote.',
        desc_en: 'Fallen wires, sparking panels or signs of a gas leak — always photographed from a distance, never up close.',
      },
      {
        es: '💡 Ángulo y luz',
        en: '💡 Angle and light',
        desc_es: 'Si una pared está inclinada, tómala de perfil (desde un lado) para que se note la inclinación. Usa luz natural cuando puedas; si usas flash, hazlo en ángulo para que se vean bien las sombras de la grieta.',
        desc_en: 'If a wall is leaning, shoot it from the side so the lean is visible. Use natural light when possible; if you use flash, angle it so the crack\'s shadows show clearly.',
      },
    ],
  },
  {
    id: 'reportar',
    emoji: '📋',
    es: 'Cómo reportar un edificio dañado correctamente',
    en: 'How to correctly report a damaged building',
    color: '#1A5276',
    bg: '#EBF5FB',
    border: '#AED6F1',
    items: [
      {
        es: '📍 Información mínima necesaria',
        en: '📍 Minimum required information',
        desc_es: 'Para un reporte útil necesitas: dirección o referencia clara, ciudad, nivel de daño visible, y si hay personas atrapadas o riesgos activos.',
        desc_en: 'For a useful report you need: clear address or reference, city, visible damage level, and whether there are trapped people or active risks.',
      },
      {
        es: '📸 Fotos solo desde lugar seguro',
        en: '📸 Photos only from a safe location',
        desc_es: 'No te arriesgues para obtener una mejor foto. Una foto desde lejos es mejor que ninguna foto y un reportante lesionado.',
        desc_en: 'Do not take risks for a better photo. A photo from far away is better than no photo and an injured reporter.',
      },
      {
        es: '🔁 Actualiza en lugar de duplicar',
        en: '🔁 Update instead of duplicating',
        desc_es: 'Busca si el edificio ya existe en CRIS antes de crear un reporte nuevo. Es mejor agregar información a un reporte existente.',
        desc_en: 'Check if the building already exists in CRIS before creating a new report. It is better to add information to an existing report.',
      },
      {
        es: '✅ Solo reporta lo que viste',
        en: '✅ Only report what you saw',
        desc_es: 'No publiques rumores ni información de segunda mano sin confirmar. Indica si tu información es directa, te la contaron, o la viste en foto.',
        desc_en: "Do not publish rumors or unconfirmed secondhand information. Indicate whether your information is direct, told to you, or seen in a photo.",
      },
      {
        es: '📞 Escribe tu contacto (es privado)',
        en: '📞 Write your contact (it is private)',
        desc_es: 'Tu teléfono y email nunca se publican. Solo son usados si una institución necesita contactarte para verificar el reporte.',
        desc_en: 'Your phone and email are never published. They are only used if an institution needs to contact you to verify the report.',
      },
    ],
  },
];