import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

function genToken() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let t = '';
  for (let i = 0; i < 32; i++) t += chars[Math.floor(Math.random() * chars.length)];
  return t;
}

function inyectarAntiExtorsion(html, es) {
  const msg = es
    ? '⚠️ Nunca envíes dinero a cambio de información. STATUSVZLA.com no autoriza pagos ni rescates privados. Si alguien pide dinero, es una estafa.'
    : '⚠️ Never send money in exchange for information. STATUSVZLA.com does not authorize payments or private rescue fees. If someone asks for money, it\'s a scam.';
  return html.replace('{{ANTI_EXTORSION}}', msg);
}

function buildHtml({ tipo, nombre, estadoLabel, estadoColor, ubicacion, mensaje, profileLink, updateLink, es }) {
  const headerTitle = es ? `${tipo}: ${nombre}` : `${tipo}: ${nombre}`;

  return `<!DOCTYPE html><html lang="${es ? 'es' : 'en'}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${headerTitle}</title></head>
<body style="margin:0;padding:0;background:#F4F4F8;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F4F4F8;padding:24px 16px;">
<tr><td align="center">
<table width="100%" style="max-width:520px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
<tr><td style="background:#1A1F2E;padding:20px 28px;">
  <p style="margin:0;color:#fff;font-size:20px;font-weight:900;">STATUS<span style="color:#D48C2E;">VZLA</span><span style="color:#D48C2E;font-size:14px;">.com</span></p>
  <p style="margin:4px 0 0;color:#9CA3AF;font-size:11px;">${es ? 'Sistema de respuesta a emergencias · Venezuela' : 'Emergency response system · Venezuela'}</p>
</td></tr>
<tr><td style="padding:24px 28px 12px;">
  <div style="background:${estadoColor || '#FFF8EE'};border-radius:12px;padding:18px;text-align:center;">
    <h2 style="margin:0;font-size:20px;font-weight:900;color:#1A1F2E;">${nombre}</h2>
    ${estadoLabel ? `<p style="margin:8px 0 0;display:inline-block;background:#1A1F2E;color:#fff;font-size:12px;font-weight:700;padding:4px 14px;border-radius:50px;">${estadoLabel}</p>` : ''}
    ${ubicacion ? `<p style="margin:8px 0 0;font-size:12px;color:#6B7280;">📍 ${ubicacion}</p>` : ''}
  </div>
</td></tr>
${mensaje ? `<tr><td style="padding:0 28px 16px;"><p style="margin:0;font-size:14px;color:#4B5563;line-height:1.5;background:#F9FAFB;border-radius:10px;padding:14px;">"${mensaje}"</p></td></tr>` : ''}
<tr><td style="padding:0 28px 16px;">
  <p style="margin:0;font-size:13px;color:#6B7280;line-height:1.5;">
    ${es ? 'Recibiste esta notificación porque sigues esta información en StatusVzla.' : 'You received this notification because you follow this information on StatusVzla.'}
  </p>
</td></tr>
<tr><td style="padding:0 28px 16px;">
  <a href="${profileLink}" style="display:block;background:#1A1F2E;color:#fff;text-decoration:none;text-align:center;padding:14px;border-radius:10px;font-weight:700;font-size:14px;margin-bottom:8px;">
    ${es ? '🔍 Ver información completa' : '🔍 View full information'}
  </a>
  ${updateLink ? `<a href="${updateLink}" style="display:block;background:#fff;border:2px solid #D48C2E;color:#D48C2E;text-decoration:none;text-align:center;padding:12px;border-radius:10px;font-weight:700;font-size:13px;">
    ${es ? '🔄 Tengo información' : '🔄 I have information'}</a>` : ''}
</td></tr>
<tr><td style="padding:0 28px 16px;">
  <div style="background:#FDF1F0;border:1px solid #E8B4B0;border-radius:10px;padding:12px;">
    <p style="margin:0;font-size:11px;color:#B83A52;line-height:1.5;">{{ANTI_EXTORSION}}</p>
  </div>
</td></tr>
<tr><td style="background:#F9FAFB;padding:16px 28px;border-top:1px solid #F3F4F6;">
  <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.5;">
    ${es ? 'Este mensaje fue generado automáticamente por STATUSVZLA.com — Sistema de respuesta a emergencias.' : 'This message was automatically generated by STATUSVZLA.com — Emergency response system.'}
  </p>
</td></tr>
</table></td></tr></table></body></html>`;
}

const APP_URL = 'https://app.statusvzla.com';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const payload = await req.json();
    console.log('notificarTodo payload:', JSON.stringify(payload));
    const { tipo, entidad_id, nombre, estado_label, estado_color, ubicacion, mensaje, reportante_nombre, lang } = payload;

    if (!tipo || !entidad_id) {
      return Response.json({ error: 'tipo y entidad_id requeridos' }, { status: 400 });
    }

    // 1. Suscriptores directos (Suscripciones para personas)
    const subsDirectos = await base44.asServiceRole.entities.Suscripciones.filter({
      persona_id: entidad_id,
      activa: true,
    });

    // 2. Suscriptores via segumiento (SuscriptoresSeguimiento para edificios)
    const subsEdificio = await base44.asServiceRole.entities.SuscriptoresSeguimiento.filter({
      reporte_id: entidad_id,
      activo: true,
    });

    // 3. Suscriptores via grupos
    let subsGrupo = [];
    try {
      const grupos = await base44.asServiceRole.entities.GruposNotificacion.filter({
        entidad_ids: { $contains: entidad_id },
      });
      subsGrupo = grupos.flatMap(g => g.suscriptores || []);
    } catch (_) {
      // fallback: cargar todos los grupos y barrer en el cliente
      try {
        const grupos = await base44.asServiceRole.entities.GruposNotificacion.list('-created_date', 100);
        subsGrupo = grupos
          .filter(g => (g.entidad_ids || []).includes(entidad_id))
          .flatMap(g => g.suscriptores || []);
      } catch (_) { /**/ }
    }

    const todosLosEmails = new Set([
      ...subsDirectos.map(s => s.email_notificacion).filter(Boolean),
      ...subsEdificio.map(s => s.telefono_whatsapp || s.email_notificacion).filter(Boolean),
      ...subsGrupo,
    ]);

    const es = lang !== 'en';
    const expira = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();
    const token = genToken();

    // Guardar token de acceso
    await base44.asServiceRole.entities.TokensAutoUpdate.create({
      token,
      persona_id: entidad_id,
      email_destino: `${tipo}-${entidad_id}`,
      usado: false,
      expira,
    });

    const tipoLabel = { es: { persona: 'Persona', edificio: 'Edificio', refugio: 'Refugio', institucional: 'Reporte' },
      en: { persona: 'Person', edificio: 'Building', refugio: 'Shelter', institucional: 'Report' } };
    const tipoEs = tipoLabel.es[tipo] || 'Actualización';
    const tipoEn = tipoLabel.en[tipo] || 'Update';

    const profileLink = tipo === 'persona'
      ? `${APP_URL}/persona?id=${entidad_id}&token=${token}`
      : `${APP_URL}/edificio?id=${entidad_id}&token=${token}`;
    const updateLink = tipo === 'persona'
      ? `${APP_URL}/actualizar-estado?token=${token}`
      : `${APP_URL}/actualizar-estado?ref=edificio&id=${entidad_id}&token=${token}`;

    const baseHtml = buildHtml({
      tipo: es ? tipoEs : tipoEn,
      nombre,
      estadoLabel: estado_label,
      estadoColor: estado_color,
      ubicacion,
      mensaje,
      profileLink,
      updateLink,
      es,
    });
    const finalHtml = inyectarAntiExtorsion(baseHtml, es);

    const asunto = es
      ? `StatusVzla | ${tipoEs}: ${nombre}${estado_label ? ` — ${estado_label}` : ''}`
      : `StatusVzla | ${tipoEn}: ${nombre}${estado_label ? ` — ${estado_label}` : ''}`;

    let enviados = 0;
    for (const email of todosLosEmails) {
      try {
        await base44.asServiceRole.integrations.Core.SendEmail({
          to: email,
          subject: asunto,
          body: finalHtml,
          from_name: 'StatusVzla',
        });
        enviados++;
      } catch (e) {
        console.warn(`Error enviando a ${email}: ${e.message}`);
      }
    }

    return Response.json({
      ok: true, enviados, total: todosLosEmails.size, token, asunto,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});