import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

function genToken() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let t = '';
  for (let i = 0; i < 32; i++) t += chars[Math.floor(Math.random() * chars.length)];
  return t;
}

const APP_URL = 'https://app.statusvzla.com';

function buildEmailHtml({ nombre, nivel_dano_desc, personaNombre, direccion, reportanteNombre, token, lang }) {
  const es = lang !== 'en';
  const profileLink = `${APP_URL}/persona?token=${token}`;
  const updateLink = `${APP_URL}/actualizar-edificio?token=${token}`;

  return `<!DOCTYPE html>
<html lang="${es ? 'es' : 'en'}">
<head><meta charset="UTF-8"><title>STATUSVZLA</title></head>
<body style="margin:0;padding:0;background:#F4F4F8;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F4F4F8;padding:24px 16px;">
    <tr><td align="center">
      <table width="100%" style="max-width:520px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08);">
        <tr><td style="background:#1A1F2E;padding:20px 28px;">
          <p style="margin:0;color:#fff;font-size:20px;font-weight:900;letter-spacing:-0.5px;">STATUS<span style="color:#D48C2E;">VZLA</span><span style="color:#D48C2E;font-size:14px;">.com</span></p>
          <p style="margin:4px 0 0;color:#9CA3AF;font-size:11px;">${es ? 'Sistema de respuesta a emergencias · Venezuela' : 'Emergency response system · Venezuela'}</p>
        </td></tr>
        <tr><td style="padding:24px 28px 12px;">
          <div style="background:#FDEDEC;border:1px solid #F5B7B1;border-radius:12px;padding:18px;text-align:center;">
            <p style="margin:0 0 6px;font-size:13px;color:#9CA3AF;font-weight:600;text-transform:uppercase;">${es ? 'Actualización de edificio' : 'Building update'}</p>
            <h2 style="margin:0 0 6px;font-size:20px;font-weight:900;color:#1A1F2E;">${nombre || (es ? 'Edificio reportado' : 'Reported building')}</h2>
            ${direccion ? `<p style="margin:0;font-size:13px;color:#6B7280;">📍 ${direccion}</p>` : ''}
            ${nivel_dano_desc ? `<p style="margin:8px 0 0;display:inline-block;background:#C0392B;color:#fff;font-size:12px;font-weight:700;padding:4px 14px;border-radius:50px;">${nivel_dano_desc}</p>` : ''}
          </div>
        </td></tr>
        <tr><td style="padding:0 28px 16px;">
          <p style="margin:0;font-size:14px;color:#374151;line-height:1.6;">
            ${es
              ? `Recibiste esta alerta porque te registraste para recibir actualizaciones sobre este edificio.${personaNombre ? ` El reportante ${personaNombre} actualizó el estado.` : ''}`
              : `You received this alert because you subscribed to updates on this building.${personaNombre ? ` The reporter ${personaNombre} updated the status.` : ''}`}
          </p>
        </td></tr>
        <tr><td style="padding:0 28px 16px;">
          <a href="${profileLink}" style="display:block;background:#1A1F2E;color:#fff;text-decoration:none;text-align:center;padding:14px;border-radius:10px;font-weight:700;font-size:14px;margin-bottom:8px;">
            ${es ? '🔍 Ver ficha completa del edificio' : '🔍 View full building record'}
          </a>
          <a href="${updateLink}" style="display:block;background:#fff;border:2px solid #C0392B;color:#C0392B;text-decoration:none;text-align:center;padding:12px;border-radius:10px;font-weight:700;font-size:13px;">
            ${es ? '🔄 Tengo información sobre este edificio' : '🔄 I have info about this building'}
          </a>
        </td></tr>
        <tr><td style="padding:0 28px 16px;">
          <div style="background:#FDF1F0;border:1px solid #E8B4B0;border-radius:10px;padding:12px;">
            <p style="margin:0;font-size:11px;color:#B83A52;line-height:1.5;">
              ⚠️ ${es
                ? 'No entres a estructuras dañadas. No envíes dinero a cambio de información. StatusVzla no autoriza rescates privados ni intermediarios anónimos.'
                : 'Do not enter damaged structures. Never send money for information. StatusVzla does not authorize private rescues or anonymous intermediaries.'}
            </p>
          </div>
        </td></tr>
        <tr><td style="background:#F9FAFB;padding:16px 28px;border-top:1px solid #F3F4F6;">
          <p style="margin:0;font-size:11px;color:#9CA3AF;text-align:center;line-height:1.5;">
            ${es ? 'Este mensaje fue generado automáticamente por STATUSVZLA.com — Sistema de respuesta a emergencias.' : 'This message was automatically generated by STATUSVZLA.com — Emergency response system.'}
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const { edificio_id, nivel_dano, direccion, nombre_lugar, reportante_nombre, lang } = await req.json();

    if (!edificio_id) return Response.json({ error: 'edificio_id requerido' }, { status: 400 });

    const subs = await base44.asServiceRole.entities.SuscriptoresSeguimiento.filter({
      reporte_id: edificio_id,
      tipo_reporte: 'dano',
      activo: true,
    });

    if (!subs || subs.length === 0) {
      // Si no hay suscriptores, igual creamos un token para que quien reportó pueda acceder sin login
      return Response.json({ ok: true, notificados: 0, flat: true });
    }

    const nivelLabels = {
      leve:       { es: 'Daño leve',            en: 'Minor damage' },
      moderado:   { es: 'Daño moderado',         en: 'Moderate damage' },
      grave:      { es: 'Daño grave — NO ENTRAR', en: 'Severe damage — DO NOT ENTER' },
      critico:    { es: 'CRÍTICO — NO ENTRAR',    en: 'CRITICAL — DO NOT ENTER' },
      colapsado:  { es: 'COLABSADO — EVACUADO',   en: 'COLLAPSED — EVACUATED' },
      no_evaluado:{ es: 'Sin evaluar',             en: 'Not evaluated' },
    };

    const nivelDesc = nivelLabels[nivel_dano]?.[lang === 'en' ? 'en' : 'es'] || nivel_dano;
    const asunto = lang === 'en'
      ? `🏗️ Update: ${nombre_lugar || 'Building'}`
      : `🏗️ Actualización: ${nombre_lugar || 'Edificio'}`;

    let notificados = 0;
    const now = Date.now();
    const expira = new Date(now + 30 * 24 * 60 * 60 * 1000).toISOString();
    const token = genToken();
    await base44.asServiceRole.entities.TokensAutoUpdate.create({
      token, persona_id: edificio_id, email_destino: 'edificio-' + edificio_id,
      usado: false, expira,
    });

    for (const sub of subs) {
      const html = buildEmailHtml({
        nombre: nombre_lugar,
        nivel_dano_desc: nivelDesc,
        direccion,
        reportanteNombre: reportante_nombre,
        token,
        lang: lang || 'es',
      });

      try {
        await base44.asServiceRole.integrations.Core.SendEmail({
          to: sub.telefono_whatsapp,
          subject: asunto,
          body: html,
          from_name: 'STATUSVZLA.com',
        });
        notificados++;
      } catch (e) {
        console.warn(`Error enviando a ${sub.telefono_whatsapp}: ${e.message}`);
      }
    }

    return Response.json({ ok: true, notificados, token });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});